apiVersion: database.example.org/v1alpha1
kind: PostgreSQLInstance
metadata:
  name: sample-api-db
spec:
  parameters:
    storageGB: 20
  compositionSelector:
    matchLabels:
      provider: aws
      vpc: default
  writeConnectionSecretToRef:
    name: sample-api-db-conn
