apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: sample-api
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: "sample-api"
spec:
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1" # stop the workload scaling to 0 for debugging
  source:
    git:
      url: https://github.com/asaikali/sample-api-accelerator.git
      ref:
        branch: main
  serviceClaims:
    - name: cloudsql-postgres
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ResourceClaim
        name: cloudsql-postgres-claim # name must match the service claim name
